# Use the official Node.js 14 image as base
FROM node:19.9.0

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the port your app runs on
EXPOSE 3002

# Command to run your app
CMD ["npm", "run", "start-backend"]
